### ISSUE TITLE
Can't use function inside of the component

### ISSUE THREAD

**Issue by gdulus** [Frozenlock/reagent-modals#1]
Hey 

First of all, great job with this modal. I have one question about things i can pass to it.  In code there is docu that parameter for modal! function takes normal Reagent component, which should include this:

```
(defn presenter []
  (let [seconds-elapsed (atom 0)]
    (fn []
      (js/setTimeout #(swap! seconds-elapsed inc) 1000)
      [:div
       "Seconds Elapsed: " @seconds-elapsed])))

(reagent-modals/modal!  (presenter) {:size :lg})
```

but unfortunately its not rendered for me. Am I doing something wrong?

**Comment by Frozenlock** [comment]
It appears that you are calling the function, instead of the usual component call (square brackets).

Try this instead:

``` clj
(reagent-modals/modal!  [presenter] {:size :lg})
```

Let me know how it goes.

**Comment by gdulus** [comment]
Yes. Works like a charm. Maybe it would be good idea to add it as example to the docu?
