### ISSUE TITLE
Function to close a modal?

### ISSUE THREAD

**Issue by yayitswei** [Frozenlock/reagent-modals#2]
Hi, thanks for making reagent-modals. Is there a clean way to close a modal programmatically? My use case is when a user clicks on a button within a modal, it swaps the dom to another screen (via Reagent). This removes the modal but leaves the `modal-open` class on the body. I could just remove that class manually, but it seems kind of hacky.

**Comment by Frozenlock** [comment]
Untested, but something like this should do the trick:

``` clj
;; within the reagent-modal namespace

(let [m (js/jQuery (get-modal))]
    (.call (aget m "modal") m "hide"))
```

Let me know if it works.

**Comment by Frozenlock** [comment]
Added as `close-modal!` in the new version.
