### ISSUE TITLE
Cannot read property 'call' of undefined(…)

### ISSUE THREAD

**Issue by analyticbastard** [Frozenlock/reagent-modals#4]
```(aget m "modal")``` is nil in the first call in the function.

```clojure
(defn- with-opts [opts]
  (let [m (js/jQuery (get-modal))]
    (.call (aget m "modal") m opts)
    (.call (aget m "modal") m "show")
    m))
```

Is this project up to date? I've got all libraries with the suggested versions in place and I get this error.

**Comment by Frozenlock** [comment]
Do you have the `modal-window` component somewhere in your document?

**Comment by analyticbastard** [comment]
I added bootstrap.min.js and the previous error is gone. I get nothing now, however. No errors, no modal.

I followed the steps mentioned in the readme and in the Youtube video about the reagent recipe.

Will investigate more tomorrow.

**Comment by Frozenlock** [comment]
So, you've added the required JS (bootstrap and jquery).
Do you have `modal-window` somewhere in your document? It should _always_ be present.

It would also help if you could post your code.

**Comment by analyticbastard** [comment]
My problem was a bad bootstrap URL that I hadn't noticed.

Yes the `modal-window` is added into the main app component.

``` clojure
(defn main-container-component []
  [:div
   (navbar-component)
   (contents-component)
   [reagent-modals/modal-window]]
  )

(defn render! []
  (r/render [main-container-component] app)
  )
```

and then I've got a handler for on-click ``{:on-click #(reagent-modals/modal! [:div "some message to the user!"])`

The `with-opts` is definitely getting executed.

Thanks.

**Comment by Frozenlock** [comment]
Great. Let me know if you encounter other problems. :wink:
